/**
 * Visual baselines (T-010, §8.1.3 "Visual"), written against TODAY's shipped UI.
 *
 * Screenshots EVERY screen the smoke layer covers — the same runtime menu discovery
 * (helpers/menu.js: window.cmplz_settings.menu), so a menu item added or removed in PHP is
 * picked up with no spec edit — at two viewport widths, 1440px and 768px. The capture scope is
 * the app container (`#complianz`, the PHP mount node / kept scope anchor, ADR-001), NOT the full
 * page: WordPress admin chrome is baselined separately in isolation.spec.js (DB-01/DB-02), so
 * keeping it out here makes each baseline smaller and free of the browser-fetched admin-bar
 * gravatar. These are the look-preserving baseline for Phases 1-2 (SC-06/SC-07): every later task
 * must keep them unchanged, so determinism is the whole point.
 *
 * Runs in `admin` (en_US) now; the `admin-rtl` (he_IL) baselines are generated by T-013 from this
 * same spec (playwright.config.js matches it in both projects, and snapshotPathTemplate splits per
 * project). Nothing here hard-codes an English title or a locale — discovery is by the app's own
 * menu data and screens are addressed by their deep-link hash (the preserved C-3 contract).
 *
 * Selector contract (§8.1.1): discovery/navigation use role / name / text; the only raw selectors
 * are the `#complianz` scope anchor (via helpers/menu.js) and the dynamic-region masks below, which
 * are necessarily tied to today's rendered markup (a mask is a visual, not a navigation, concern).
 *
 * SNAPSHOT UPDATE POLICY (ADR-008 / §8.1.3): the committed PNGs under
 * tests/e2e/admin/__screenshots__/ are the review reference. They are regenerated ONLY by an
 * explicitly reviewed PR that runs `npm run e2e -- --update-snapshots` and shows the image diff —
 * never silently. A redesign task re-baselines a screen only when its look is intentionally changed.
 */

const { test, expect } = require( '@playwright/test' );
const { discoverPages, gotoSettings, expectContentLoaded, APP } = require( './helpers/menu' );

// The two widths of the visual layer (§8.1.3): 1440 desktop and 768 tablet. Height is generous so
// above-the-fold data is in; the element screenshot captures the full #complianz box regardless.
const WIDTHS = [
	{ w: 1440, h: 900 },
	{ w: 768, h: 1024 },
];

// Reused from axe.spec.js: a filesystem-safe, locale-independent id for a page hash.
function slug( hash ) {
	return hash.replace( /^#/, '' ).replace( /[^a-z0-9]+/gi, '_' );
}

/**
 * Dynamic regions masked out of every per-screen shot (the S3 calibration record). Each mask is a
 * locator; `toHaveScreenshot` overlays the matches and silently ignores the ones a given screen does
 * not contain, so one list is safe for all 37 screens. We MASK rather than raise the threshold
 * (task guidance) so a real regression anywhere else still fails. Every entry says why:
 */
function dynamicMasks( page ) {
	return [
		// Loading placeholders: `.cmplz-placeholder-line` widths are baked by SCSS `random()` at
		// BUILD time (assets/css/admin/modules/placeholder.scss), so they differ on every rebuild
		// (learnings 2026-10-06). We wait for real content before shooting, but a slow async sub-panel
		// can still show one; masking it keeps a stray placeholder from ever diffing.
		page.locator( '.cmplz-placeholder' ),
		// Scan / cookiedatabase-sync progress bars: width is driven by scan state and timing
		// (CookieScanControl.js, CookieDatabaseSyncControl.js), not by the seed.
		page.locator( '.cmplz-progress-bar' ),
		// Settings footer scroll-position indicator: its width tracks the scroll offset (Settings.js),
		// which depends on content height and so drifts between widths/renders.
		page.locator( '.cmplz-grid-item-footer-scroll-progress' ),
	];
}

// The banner section (5 screens) needs extra settling and preview handling, for two reasons:
//
//  1. The banner settings FORM has fields gated by `react_conditions` whose controlling values are
//     filled asynchronously from the banner record (CookieBannerPreview syncs banner -> fields). Until
//     that sync lands, a conditional row is absent and everything below it sits one row too high —
//     the exact run-to-run shift seen in calibration. The preview component returns null until
//     `bannerToFieldsSynced` is true (CookieBannerPreview.js), so waiting for the injected banner to
//     appear is a reliable "the form has settled" signal.
//  2. That preview is position:fixed, so it paints over the app container's bottom corner, and which
//     of its states shows (banner vs manage-consent) flips on every React re-render. Masking its
//     0-height id-containers does not cover the escaping fixed children, so we hide the whole preview
//     subtree instead (position:fixed, so hiding causes no reflow). The preview is baselined precisely,
//     per layout, at 1920x1080 in isolation.spec.js (ADR-008).
//
// Poll an element's height until it stops changing for a few consecutive samples — a generic "the
// layout has settled" wait. On the banner screens the `consent_type` sync cascade toggles a
// conditional row (e.g. "Categories display options") a beat AFTER the preview first appears, which
// changes the form's height; without this the shot can land mid-cascade and the whole form sits one
// row off (the exact calibration flake). `toHaveScreenshot`'s own frame-stabilisation does not cover
// it because each individual frame is briefly stable between cascade steps.
async function waitForStableHeight( page, selector, { samples = 4, interval = 400, timeout = 20_000 } = {} ) {
	const start = Date.now();
	let last = -1;
	let stable = 0;
	while ( Date.now() - start < timeout ) {
		const h = await page
			.locator( selector )
			.evaluate( ( el ) => Math.round( el.getBoundingClientRect().height ) )
			.catch( () => -1 );
		if ( h > 0 && h === last ) {
			if ( ++stable >= samples ) {
				return;
			}
		} else {
			stable = 0;
			last = h;
		}
		await page.waitForTimeout( interval );
	}
}

// Keyed on the stable menu section id (`banner`), never a localized title, so it is RTL-safe for T-013.
async function settleAndHideBannerPreview( page, info, appSelector ) {
	if ( info.section === 'banner' ) {
		// First the sync signal: the preview renders only once banner->fields sync completes.
		await page
			.locator( '#cmplz-preview-banner-container .cmplz-cookiebanner' )
			.waitFor( { state: 'visible', timeout: 30_000 } )
			.catch( () => {} );
		// The consent_type sync that fires AFTER the preview appears re-fetches the fields over REST
		// (even with consent_type seeded, setChangedField still runs the cascade), which briefly drops
		// and re-adds the conditional "Categories" row. We gate on that settling with THREE real signals,
		// not a fixed delay: (1) network idle so any in-flight /fields/get finishes; (2) the form height
		// holds steady; (3) network idle again and the height STILL holds — this second pass catches a
		// late re-fetch that fired just after the first height settled (the ~8% 768 flake). The preview
		// itself is hidden below, so the racy banner-link render never reaches these shots.
		await page.waitForLoadState( 'networkidle', { timeout: 10_000 } ).catch( () => {} );
		await waitForStableHeight( page, appSelector, { samples: 8, interval: 500, timeout: 30_000 } );
		await page.waitForLoadState( 'networkidle', { timeout: 10_000 } ).catch( () => {} );
		await waitForStableHeight( page, appSelector, { samples: 8, interval: 500, timeout: 30_000 } );
	}
	await page
		.addStyleTag( { content: '#cmplz-preview-banner-container{display:none !important;}' } )
		.catch( () => {} );
}

// One test, ~37 screens x 2 widths. Serial, one worker (shared wp-env DB); give it room.
test.describe.configure( { mode: 'serial', timeout: 1_200_000 } );

// Optional CPU-throttling knob (no-op unless E2E_CPU_THROTTLE is set): slows the renderer so the
// determinism of the signal-based settle waits does not depend on machine speed. Used to verify the
// baselines hold under load; off in normal/CI runs.
test.beforeEach( async ( { page } ) => {
	const rate = Number( process.env.E2E_CPU_THROTTLE );
	if ( rate > 1 ) {
		const client = await page.context().newCDPSession( page );
		await client.send( 'Emulation.setCPUThrottlingRate', { rate } );
	}
} );

test( 'every smoke screen is visually stable at 1440 and 768 (app container)', async ( { page } ) => {
	const pages = await discoverPages( page );
	expect( pages.length, 'menu discovery found no screens' ).toBeGreaterThan( 0 );

	const app = page.locator( APP );
	// Aggregate unstable screens and report them together (like smoke), instead of stopping at the
	// first diff — so one run shows every screen that moved.
	const failures = [];

	for ( const info of pages ) {
		for ( const { w, h } of WIDTHS ) {
			await test.step( `${ slug( info.hash ) } @${ w }`, async () => {
				await page.setViewportSize( { width: w, height: h } );
				await gotoSettings( page, info.hash );
				// Positive "real content is in" wait (never a placeholder-class check) — same gate the
				// smoke layer uses, so we never shoot a stuck/loading screen.
				await expectContentLoaded( page, info );
				// Let any late /complianz/v1/ data for this screen settle before the shot.
				await page.waitForLoadState( 'networkidle', { timeout: 10_000 } ).catch( () => {} );
				// On banner screens: wait for the async form sync + layout settle, then hide the preview.
				await settleAndHideBannerPreview( page, info, APP );
				try {
					await expect( app ).toHaveScreenshot( `${ slug( info.hash ) }-${ w }.png`, {
						mask: dynamicMasks( page ),
					} );
				} catch ( err ) {
					failures.push( `${ info.hash } @${ w }: ${ String( err.message || err ).split( '\n' )[ 0 ] }` );
				}
			} );
		}
	}

	expect( failures, 'screens whose app container did not match its visual baseline' ).toEqual( [] );
} );
