/**
 * Wizard flow layer (T-012, §8.1.3), `admin` project (8888, latest), TODAY's UI.
 *
 * Characterises the guided setup wizard: stepping through steps with Next/Previous, the progress
 * indicator advancing, the Finish step, and the generated documents — all in the seeded fixture.
 *
 * Determinism (§8.1.2): one worker, shared fixture DB. Clicking a wizard "Save and Continue"/
 * "Continue" control SAVES the current step (Settings.js saveData), which would write to
 * `cmplz_options`. To keep the DB byte-identical for every sibling spec (and the visual baseline in
 * a combined CI run), every test here STUBS `/complianz/v1/fields/set` so the save is a no-op while
 * the hash navigation (driven by the link's own href, the C-3 deep-link contract) still happens.
 * Nothing in this file mutates the DB; the documents assertion only reads the dashboard.
 *
 * Selector contract (§8.1.1): role / accessible name / text / `data-testid`, plus `aria-current`.
 * The active wizard step carries `aria-current="step"` (added to Menu/MenuItem.js by this task — an
 * attribute-only, behaviour-free a11y hook, so the T-010 pixel baselines are unaffected), which is
 * the accessible "progress indicator": it moves to the step you are on. Steps are addressed by their
 * stable hash (`#wizard/<id>`), never an English title, so this survives the RTL/i18n projects and
 * the Phase-2 primitive migration. No `cmplz-*`, WP-core or utility class selector appears.
 *
 * NOTE (characterised, reported for /flow:clarify): the minimal seed intentionally leaves required
 * wizard questions unanswered (the dashboard's "Not all fields have been entered" task, the Finish
 * control's "questions that are required to complete the wizard" summary). TODAY that means the
 * footer **Finish button is disabled** and `finish()` returns early (Settings.js) — the wizard
 * cannot be "completed" from the pure seed. This spec therefore characterises the Finish step in its
 * real seeded state (rendered, summarising outstanding questions, button disabled) rather than
 * forcing an artificial all-complete state. The documents are generated by the seed regardless, and
 * that is asserted independently.
 */

const { test, expect } = require( '@playwright/test' );
const {
	APP,
	gotoSettings,
	waitForAppMounted,
	waitForSectionLoaded,
} = require( './helpers/menu' );

// Keep every wizard save a no-op so navigation never mutates the shared DB (see header).
async function stubSaves( page ) {
	await page.route( /complianz\/v1\/fields\/set/, ( route ) =>
		route.fulfill( { status: 200, contentType: 'application/json', body: JSON.stringify( { request_success: true, fields: false } ) } )
	);
	// The app falls back to admin-ajax only if the REST call fails; stub that path too, defensively.
	await page.route( /admin-ajax\.php/, ( route ) => {
		const body = route.request().postData() || '';
		if ( body.includes( 'fields/set' ) ) {
			return route.fulfill( { status: 200, contentType: 'application/json', body: JSON.stringify( { request_success: true, fields: false } ) } );
		}
		return route.continue();
	} );
}

const nextControl = ( page ) => page.locator( APP ).getByRole( 'link', { name: /^(Save and Continue|Continue)$/ } );
const previousControl = ( page ) => page.locator( APP ).getByRole( 'link', { name: 'Previous', exact: true } );
const currentStepHref = ( page ) => page.locator( APP ).locator( '[aria-current="step"]' ).first().getAttribute( 'href' );

test.describe.configure( { mode: 'serial', timeout: 300_000 } );

test.beforeEach( async ( { page } ) => {
	await stubSaves( page );
} );

test( 'Next steps through the wizard and the progress indicator advances', async ( { page } ) => {
	await gotoSettings( page, '#wizard' );
	await waitForSectionLoaded( page, 'Wizard' );

	// The progress indicator: the sidebar marks exactly one current step via aria-current="step".
	const first = await currentStepHref( page );
	expect( first, 'wizard did not mark a current step' ).toBeTruthy();

	const visitedHashes = [ await page.evaluate( () => window.location.hash ) ];
	const indicatorTrail = [ first ];

	// Walk forward via the Next control. Each click follows the step's own hash link; we assert the
	// hash advances and the progress indicator moves with it. In the seeded state the chain advances
	// through several steps and then the Next control gates on an unanswered required question (today's
	// real behaviour) — we stop at the first step that does not advance.
	for ( let i = 0; i < 20; i++ ) {
		const before = await page.evaluate( () => window.location.hash );
		if ( ( await nextControl( page ).count() ) === 0 ) {
			break; // the Finish step shows "Finish" instead of a Next control.
		}
		await nextControl( page ).first().click();
		const advanced = await page
			.waitForFunction( ( h ) => window.location.hash !== h, before, { timeout: 8_000 } )
			.then( () => true )
			.catch( () => false );
		if ( ! advanced ) {
			break; // required-question gate (Next points back at the same step).
		}
		await waitForSectionLoaded( page, 'Wizard' );
		const h = await page.evaluate( () => window.location.hash );
		// Let the indicator catch up to the new step before recording it (the menu re-renders a tick
		// after the hash changes).
		await expect( page.locator( APP ).locator( '[aria-current="step"]' ).first() ).toHaveAttribute( 'href', h, { timeout: 8_000 } );
		visitedHashes.push( h );
		indicatorTrail.push( await currentStepHref( page ) );
	}

	// At least three distinct steps were reached by Next, and the indicator tracked each one.
	const distinct = [ ...new Set( visitedHashes ) ];
	expect( distinct.length, `Next did not advance across steps: ${ JSON.stringify( visitedHashes ) }` ).toBeGreaterThanOrEqual( 3 );
	// On the bare section hash (#wizard) the app auto-selects the first step, so the indicator points
	// one level deeper than the URL; once a step is in the hash (#wizard/<id>) the indicator's href
	// matches the live hash exactly — the progress indicator advanced in lock-step with navigation.
	expect( indicatorTrail[ 0 ] ).toBe( '#wizard/visitors' );
	for ( let i = 0; i < visitedHashes.length; i++ ) {
		if ( visitedHashes[ i ].includes( '/' ) && indicatorTrail[ i ] ) {
			expect( indicatorTrail[ i ] ).toBe( visitedHashes[ i ] );
		}
	}
	// And the indicator value changed as we advanced (never stuck on the first step).
	expect( [ ...new Set( indicatorTrail.filter( Boolean ) ) ].length ).toBeGreaterThanOrEqual( 3 );
} );

test( 'Previous returns to the earlier step and the indicator moves back', async ( { page } ) => {
	// Start a couple of steps in so a Previous control is present (the first step has none).
	await gotoSettings( page, '#wizard/website-information' );
	await waitForSectionLoaded( page, 'Wizard' );
	const indicator = page.locator( APP ).locator( '[aria-current="step"]' ).first();
	await expect( indicator ).toHaveAttribute( 'href', '#wizard/website-information', { timeout: 8_000 } );

	await expect( previousControl( page ).first() ).toBeVisible();
	const before = await page.evaluate( () => window.location.hash );
	await previousControl( page ).first().click();
	await page.waitForFunction( ( h ) => window.location.hash !== h, before, { timeout: 10_000 } );
	await waitForSectionLoaded( page, 'Wizard' );

	// Went back one step (documents precedes website-information) and the indicator moved with it.
	expect( await page.evaluate( () => window.location.hash ) ).toBe( '#wizard/documents' );
	await expect( indicator ).toHaveAttribute( 'href', '#wizard/documents', { timeout: 8_000 } );
} );

test( 'Finish step renders its completion summary and the Finish control', async ( { page } ) => {
	await gotoSettings( page, '#wizard/finish' );
	await waitForSectionLoaded( page, 'Wizard' );
	await expect( page.locator( APP ).locator( '[aria-current="step"]' ).first() ).toHaveAttribute( 'href', '#wizard/finish', { timeout: 8_000 } );

	const app = page.locator( APP );
	// The FinishControl summarises completion. In the seeded (intentionally incomplete) fixture it
	// lists the outstanding required questions; that text is the Finish step's contract.
	await expect(
		app.getByText( 'The following required fields have not been completed:', { exact: false } )
	).toBeVisible( { timeout: 30_000 } );

	// Two "Finish" links exist: the sidebar menu item (href="#wizard/finish") and the footer action
	// (href="#"); the footer one is last in the DOM (menu renders before the content).
	const footerFinish = app.getByRole( 'link', { name: 'Finish', exact: true } ).last();
	await expect( footerFinish ).toBeVisible();
	// TODAY, with required questions outstanding, the footer Finish is disabled (Settings.js) — the
	// wizard cannot be completed from the pure seed. Characterise that real state.
	await expect( footerFinish ).toHaveAttribute( 'disabled', '' );
} );

test( 'the seeded wizard has its legal documents generated', async ( { page } ) => {
	// The seed generates the EU legal documents (seed.php cmplz_e2e_seed_documents). The dashboard's
	// progress reflects this with a completed "all required pages generated" task — the app's own
	// documents-generated signal, read-only (no mutation).
	await gotoSettings( page, '#dashboard' );
	await waitForAppMounted( page );
	await expect(
		page.locator( APP ).getByText( 'All required pages have been generated.', { exact: false } )
	).toBeVisible( { timeout: 30_000 } );
} );
